spring.application.name=billingsystem
spring.datasource.url=jdbc:mysql://localhost:3306/billistore
spring.datasource.username=root
spring.datasource.password=bca123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true